### ISSUE TITLE
EOFError in downloadxml.py

### ISSUE THREAD

**Issue by yxwyx** [minalc44/autoimmune#1]
`Traceback (most recent call last):
  File "downloadxml.py", line 44, in <module>
    main(args)
  File "downloadxml.py", line 30, in main
    download_files(files, args)
  File "downloadxml.py", line 19, in download_files
    ftp.retrbinary("RETR " + f, open(xmldir+f, 'wb').write)
  File "/share/pkg.7/python2/2.7.16/install/lib/python2.7/ftplib.py", line 416, in retrbinary
    conn = self.transfercmd(cmd, rest)
  File "/share/pkg.7/python2/2.7.16/install/lib/python2.7/ftplib.py", line 378, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/share/pkg.7/python2/2.7.16/install/lib/python2.7/ftplib.py", line 341, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "/share/pkg.7/python2/2.7.16/install/lib/python2.7/ftplib.py", line 251, in sendcmd
    return self.getresp()
  File "/share/pkg.7/python2/2.7.16/install/lib/python2.7/ftplib.py", line 217, in getresp
    resp = self.getmultiline()
  File "/share/pkg.7/python2/2.7.16/install/lib/python2.7/ftplib.py", line 203, in getmultiline
    line = self.getline()
  File "/share/pkg.7/python2/2.7.16/install/lib/python2.7/ftplib.py", line 193, in getline
    if not line: raise EOFError
EOFError`

Hi Minal, thanks for developing this amazing tool for text mining PubMed. I encountered a problem when I try to download xml from PubMed. There is a blank file called "pubmed21n0261.xml.gz.md5" generated before this error message. Does this mean the download process already finished? Thank you in advance for your help.

**Comment by minalc44** [comment]
Hi Yuxuan,

Apologies for the late response, That error seems like a python related error rather than the code. Would it be possible to delete the file that is causing the error and try re-running the code? Alternative option would be using an FTP program to download all xml files from the NLM. 

Hope this helps,
Minal
